INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("", "", 0, "", "");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("", "", 0, "", "");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("", "", 0, "", "");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("", "", 0, "", "");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("", "", 0, "", "");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("", "", 0, "", "");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("", "", 0, "", "");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("", "", 0, "", "");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("", "", 0, "", "");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("", "", 0, "", "");

INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);
INSERT INTO users (name, age) VALUES ("", 0);

INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
INSERT INTO pledges (amount, user_id, project_id) VALUES (0, "", "");
